{% set name = "ccfits" %}
{% set version = "2.6" %}
{% set sha256 = "c8395e80379df4e2a63b0890166fb47be4b96dff977214e7ed10ea9d3e9e9a9e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/CCfits-{{ version }}.tar.gz
  folder: CCfits
  sha256: {{ sha256 }}
  patches:
    # - 0001-Add_missing_m4_macros.patch
    - 0002-Fix_CXX_LIB_PATH_macro.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - autoconf
    - libtool
    - make
  host:
    - cfitsio
  run:
    - cfitsio

test:
  commands:
    - test -f ${CONDA_PREFIX}/lib/libCCfits.so  # [linux]
    - test -f ${CONDA_PREFIX}/lib/libCCfits.dylib  # [osx]
    - test -d ${CONDA_PREFIX}/include/CCfits

about:
  summary: CCfits is an object oriented interface to the cfitsio library. It is designed to make the capabilities of cfitsio available to programmers working in C++. It is written in ANSI C++ and implemented using the C++ Standard Library with namespaces, exception handling, and member template functions.
  home: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
  license: CUSTOM
  license_file: CCfits/License.txt
  doc_url: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/html/index.html

extra:
  recipe-maintainers:
    - giacomov
    - teake
