travis:
  secure:
    BINSTAR_TOKEN: XQE6FUQEgb38LFwE3GWeA8RLjrDDfK6mpdgZ4ufpO9i0TGFZPsGeI/CFYP41BGaSp+lxDcLYmeL65GgZ92XApiMuAkLjjsZfTBEOMxV+yQaWc+rAhrbPRNEdFuahLqVPSmZz4L9wz5L4wq3zRhwn7y/vA1ETIcpk9unu1OGLjiTKU/+gZx4wueOW4Q/jM0mu66AuVS+DVx8u/8DU8QGCQ6f8ORc++K2ugIXfw898Yqs0CmDC7Uo/M3INCerKTTb7gZgYWefpYpRcE8f22Ne1CVskZZib6f8+HNL4qb+q1wBUjN1K1nspAm2edKt9hKDB9ILB0P3EAiWe5xIwtrPczLOqa6E+25mokcE5wtkxKWJhJYfAK3LD1QZtZ9OjYbz660NIL+2mmsiDl4AtmOfnPFOCWydEm5BmcqH1N+rcpmP0PysK4OILchTKnA2vafB0yW8EOkb6uBwX2WA3JEQEyFXk7oj3QxOtnRp0+rd9oNAmnUF44QUALQKkZRUeSrLx+jqSurmHb5xedTIpvNK4ZWJ17lClPHjA+bPM7FEC80rtck0ris98/Xq+ze0Qw1b4mtbkr3+wgarZsKqqiAPXMR+YjmXmpC3GrW4APxMs0d/tI2iSN6QKhx8giJCL+NVzFCDFbgaTGJE+TtwEwCGzssIdyDRa7DA+fw3Zy88rHF0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
