travis:
  secure:
    BINSTAR_TOKEN: QwrnqPMh/YP2L4svd/IEVAsRMMIpMJ8yE9L9nPU7YAOp0h6vdBmMqnq5tVQpdWBFQgHDb+xQc9JaJzppViVQ8945FqURDkNaF10wCqvPwOmCXaS8pW55x6YHhw0RpwiUgdoEI35WvLr+L/hvPRMogaQbVPG9V0YHHEXAmTYB1mgOHkjiqIjq/Nww2d3dzyy7tQHrWN2jm9JPG8yKGZQRpIixBjyHlPPTO0O/sYdiY8db5qs+Cx4HqcitnMCP4RdlE3nzVMiFs1cqBAweFl64FQq+i3O1wiQA6nubdUem6DtQve9UfcqFsYsSM9dfFK2eTt3Pr2Vnh6BguhiSz7Kyo7kq7wQNZpL11pzaZn0n6nJXBEEEyj+K9GXEXKAiP6SExExhy6anCEENu8QGTH8XXZE1q4pllvp/wcLWSCa6VQHA4CVVQP30PyjZUQrKugyMo39vnVvY5p2yJU6W7zwUrk2s8zaJLNdqfEX3R6Vl8uOLb5raPTujPAhTSl04zzeUw6OCk6CYjehHPeLgPyBDCFtFeURnAmLbLma5j1nbtIRQmrA4x72/ypJkXrtOqqc6EeEa+AX8XwhGG1yl9prLwCCclctt95uSnfo2dsalpq1Sif28LEC2+8h/SCEqcXa5vEWB3QURMu/4/Za3+DDyZkvsNWW0osxVVoJuA9+ZfTo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
